### ISSUE TITLE
Исправить  OutOfMemoryError

### ISSUE THREAD

**Issue by Kasiwadzaki** [WhiteBeef/PeacockTestTask#1]
Добрый день, меня зовут Вадим, я разработчик компании Уно-Софт.

При выполнении программы падает с ошибкой
```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.regex.Pattern$BitClass.<init>(Pattern.java:3486)
        at java.base/java.util.regex.Pattern.clazz(Pattern.java:2621)
        at java.base/java.util.regex.Pattern.sequence(Pattern.java:2139)
        at java.base/java.util.regex.Pattern.expr(Pattern.java:2069)
        at java.base/java.util.regex.Pattern.group0(Pattern.java:3050)
        at java.base/java.util.regex.Pattern.sequence(Pattern.java:2124)
        at java.base/java.util.regex.Pattern.expr(Pattern.java:2069)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1783)
        at java.base/java.util.regex.Pattern.<init>(Pattern.java:1430)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1069)
        at java.base/java.util.regex.Pattern.matches(Pattern.java:1174)
        at java.base/java.lang.String.matches(String.java:2846)
        at ru.whitebeef.SolutionWithClassGroup.main(SolutionWithClassGroup.java:55)

```

Не зависимо от того какой класс выбран. Падает как и SolutionWithClassGroup, так и SolutionWithoutClassGroup.

**Comment by WhiteBeef** [comment]
Доброго времени суток, да, была такая ошибка, если запускать код с ограничением в 1G, ему не хватало буквально 100-150МБайт.

Вот что я предпринял для решения этой проблемы:
1) Оставил только самое эффективное решение (которое больше похоже на олимпиадное программирование). 
2) Сделал сначала чтение файла отдельным методом, чтобы он не висел мертвым грузом всю задачу.
3) Изменил строки. теперь они в памяти хранятся целиком вместе с "", сразу после кавычек идет ее индекс, наподобие: `"123"9` чтобы меньше объектов строк было в памяти.
5) Сделал вывод в файл отдельным методом.
